name: Run e2e tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: api_solid_test

    steps:
    - uses: actions/checkout@v6
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v6
      with:
        node-version: '22'
        cache: 'pnpm'


    - name: Install dotenv-cli
      run: npm install -g dotenv-cli

    - run: pnpm install --frozen-lockfile
    - run: pnpm test:e2e